#!/bin/bash

USAGE="Usage: build [runner|supervisor]"

function die {
  echo $1
  exit 1
}

function build {
  docker build . -t jlimperg/mathlib-bench-"$1" --target "$1"
}

if test -z "$1"; then
  target="none"
else
  target="$1"
fi

if test "$target" == "none"; then
  build supervisor && \
  build runner
elif test "$target" == "supervisor"; then
  build supervisor
elif test "$target" == "runner"; then
  build runner
else
  die "$USAGE"
fi
